import type { Country } from "../types";

export const PREFERRED_COUNTRY_CODE = "preferredCountryCode";

export const COUNTRY_LIST: Country[] = [
  {
    name: "Afghanistan",
    iso2CountryCode: "AF",
    iso3CountryCode: "AFG",
    phoneCode: "+93",
    flagCode: "U+1F1E6 U+1F1EB",
  },
  {
    name: "Aland Islands",
    iso2CountryCode: "AX",
    iso3CountryCode: "ALA",
    phoneCode: "+358",
    flagCode: "U+1F1E6 U+1F1FD",
  },
  {
    name: "Albania",
    iso2CountryCode: "AL",
    iso3CountryCode: "ALB",
    phoneCode: "+355",
    flagCode: "U+1F1E6 U+1F1F1",
  },
  {
    name: "Algeria",
    iso2CountryCode: "DZ",
    iso3CountryCode: "DZA",
    phoneCode: "+213",
    flagCode: "U+1F1E9 U+1F1FF",
  },
  {
    name: "American Samoa",
    iso2CountryCode: "AS",
    iso3CountryCode: "ASM",
    phoneCode: "+1",
    flagCode: "U+1F1E6 U+1F1F8",
  },
  {
    name: "Andorra",
    iso2CountryCode: "AD",
    iso3CountryCode: "AND",
    phoneCode: "+376",
    flagCode: "U+1F1E6 U+1F1E9",
  },
  {
    name: "Angola",
    iso2CountryCode: "AO",
    iso3CountryCode: "AGO",
    phoneCode: "+244",
    flagCode: "U+1F1E6 U+1F1F4",
  },
  {
    name: "Anguilla",
    iso2CountryCode: "AI",
    iso3CountryCode: "AIA",
    phoneCode: "+1",
    flagCode: "U+1F1E6 U+1F1EE",
  },
  {
    name: "Antarctica",
    iso2CountryCode: "AQ",
    iso3CountryCode: "ATA",
    phoneCode: "+672",
    flagCode: "U+1F1E6 U+1F1F6",
  },
  {
    name: "Antigua and Barbuda",
    iso2CountryCode: "AG",
    iso3CountryCode: "ATG",
    phoneCode: "+1",
    flagCode: "U+1F1E6 U+1F1EC",
  },
  {
    name: "Argentina",
    iso2CountryCode: "AR",
    iso3CountryCode: "ARG",
    phoneCode: "+54",
    flagCode: "U+1F1E6 U+1F1F7",
  },
  {
    name: "Armenia",
    iso2CountryCode: "AM",
    iso3CountryCode: "ARM",
    phoneCode: "+374",
    flagCode: "U+1F1E6 U+1F1F2",
  },
  {
    name: "Aruba",
    iso2CountryCode: "AW",
    iso3CountryCode: "ABW",
    phoneCode: "+297",
    flagCode: "U+1F1E6 U+1F1FC",
  },
  {
    name: "Australia",
    iso2CountryCode: "AU",
    iso3CountryCode: "AUS",
    phoneCode: "+61",
    flagCode: "U+1F1E6 U+1F1FA",
  },
  {
    name: "Austria",
    iso2CountryCode: "AT",
    iso3CountryCode: "AUT",
    phoneCode: "+43",
    flagCode: "U+1F1E6 U+1F1F9",
  },
  {
    name: "Azerbaijan",
    iso2CountryCode: "AZ",
    iso3CountryCode: "AZE",
    phoneCode: "+994",
    flagCode: "U+1F1E6 U+1F1FF",
  },
  {
    name: "Bahrain",
    iso2CountryCode: "BH",
    iso3CountryCode: "BHR",
    phoneCode: "+973",
    flagCode: "U+1F1E7 U+1F1ED",
  },
  {
    name: "Bangladesh",
    iso2CountryCode: "BD",
    iso3CountryCode: "BGD",
    phoneCode: "+880",
    flagCode: "U+1F1E7 U+1F1E9",
  },
  {
    name: "Barbados",
    iso2CountryCode: "BB",
    iso3CountryCode: "BRB",
    phoneCode: "+1",
    flagCode: "U+1F1E7 U+1F1E7",
  },
  {
    name: "Belarus",
    iso2CountryCode: "BY",
    iso3CountryCode: "BLR",
    phoneCode: "+375",
    flagCode: "U+1F1E7 U+1F1FE",
  },
  {
    name: "Belgium",
    iso2CountryCode: "BE",
    iso3CountryCode: "BEL",
    phoneCode: "+32",
    flagCode: "U+1F1E7 U+1F1EA",
  },
  {
    name: "Belize",
    iso2CountryCode: "BZ",
    iso3CountryCode: "BLZ",
    phoneCode: "+501",
    flagCode: "U+1F1E7 U+1F1FF",
  },
  {
    name: "Benin",
    iso2CountryCode: "BJ",
    iso3CountryCode: "BEN",
    phoneCode: "+229",
    flagCode: "U+1F1E7 U+1F1EF",
  },
  {
    name: "Bermuda",
    iso2CountryCode: "BM",
    iso3CountryCode: "BMU",
    phoneCode: "+1",
    flagCode: "U+1F1E7 U+1F1F2",
  },
  {
    name: "Bhutan",
    iso2CountryCode: "BT",
    iso3CountryCode: "BTN",
    phoneCode: "+975",
    flagCode: "U+1F1E7 U+1F1F9",
  },
  {
    name: "Bolivia",
    iso2CountryCode: "BO",
    iso3CountryCode: "BOL",
    phoneCode: "+591",
    flagCode: "U+1F1E7 U+1F1F4",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    iso2CountryCode: "BQ",
    iso3CountryCode: "BES",
    phoneCode: "+599",
    flagCode: "U+1F1E7 U+1F1F6",
  },
  {
    name: "Bosnia and Herzegovina",
    iso2CountryCode: "BA",
    iso3CountryCode: "BIH",
    phoneCode: "+387",
    flagCode: "U+1F1E7 U+1F1E6",
  },
  {
    name: "Botswana",
    iso2CountryCode: "BW",
    iso3CountryCode: "BWA",
    phoneCode: "+267",
    flagCode: "U+1F1E7 U+1F1FC",
  },
  {
    name: "Bouvet Island",
    iso2CountryCode: "BV",
    iso3CountryCode: "BVT",
    phoneCode: "+0055",
    flagCode: "U+1F1E7 U+1F1FB",
  },
  {
    name: "Brazil",
    iso2CountryCode: "BR",
    iso3CountryCode: "BRA",
    phoneCode: "+55",
    flagCode: "U+1F1E7 U+1F1F7",
  },
  {
    name: "British Indian Ocean Territory",
    iso2CountryCode: "IO",
    iso3CountryCode: "IOT",
    phoneCode: "+246",
    flagCode: "U+1F1EE U+1F1F4",
  },
  {
    name: "Brunei",
    iso2CountryCode: "BN",
    iso3CountryCode: "BRN",
    phoneCode: "+673",
    flagCode: "U+1F1E7 U+1F1F3",
  },
  {
    name: "Bulgaria",
    iso2CountryCode: "BG",
    iso3CountryCode: "BGR",
    phoneCode: "+359",
    flagCode: "U+1F1E7 U+1F1EC",
  },
  {
    name: "Burkina Faso",
    iso2CountryCode: "BF",
    iso3CountryCode: "BFA",
    phoneCode: "+226",
    flagCode: "U+1F1E7 U+1F1EB",
  },
  {
    name: "Burundi",
    iso2CountryCode: "BI",
    iso3CountryCode: "BDI",
    phoneCode: "+257",
    flagCode: "U+1F1E7 U+1F1EE",
  },
  {
    name: "Cambodia",
    iso2CountryCode: "KH",
    iso3CountryCode: "KHM",
    phoneCode: "+855",
    flagCode: "U+1F1F0 U+1F1ED",
  },
  {
    name: "Cameroon",
    iso2CountryCode: "CM",
    iso3CountryCode: "CMR",
    phoneCode: "+237",
    flagCode: "U+1F1E8 U+1F1F2",
  },
  {
    name: "Canada",
    iso2CountryCode: "CA",
    iso3CountryCode: "CAN",
    phoneCode: "+1",
    flagCode: "U+1F1E8 U+1F1E6",
  },
  {
    name: "Cape Verde",
    iso2CountryCode: "CV",
    iso3CountryCode: "CPV",
    phoneCode: "+238",
    flagCode: "U+1F1E8 U+1F1FB",
  },
  {
    name: "Cayman Islands",
    iso2CountryCode: "KY",
    iso3CountryCode: "CYM",
    phoneCode: "+1",
    flagCode: "U+1F1F0 U+1F1FE",
  },
  {
    name: "Central African Republic",
    iso2CountryCode: "CF",
    iso3CountryCode: "CAF",
    phoneCode: "+236",
    flagCode: "U+1F1E8 U+1F1EB",
  },
  {
    name: "Chad",
    iso2CountryCode: "TD",
    iso3CountryCode: "TCD",
    phoneCode: "+235",
    flagCode: "U+1F1F9 U+1F1E9",
  },
  {
    name: "Chile",
    iso2CountryCode: "CL",
    iso3CountryCode: "CHL",
    phoneCode: "+56",
    flagCode: "U+1F1E8 U+1F1F1",
  },
  {
    name: "China",
    iso2CountryCode: "CN",
    iso3CountryCode: "CHN",
    phoneCode: "+86",
    flagCode: "U+1F1E8 U+1F1F3",
  },
  {
    name: "Christmas Island",
    iso2CountryCode: "CX",
    iso3CountryCode: "CXR",
    phoneCode: "+61",
    flagCode: "U+1F1E8 U+1F1FD",
  },
  {
    name: "Cocos (Keeling) Islands",
    iso2CountryCode: "CC",
    iso3CountryCode: "CCK",
    phoneCode: "+61",
    flagCode: "U+1F1E8 U+1F1E8",
  },
  {
    name: "Colombia",
    iso2CountryCode: "CO",
    iso3CountryCode: "COL",
    phoneCode: "+57",
    flagCode: "U+1F1E8 U+1F1F4",
  },
  {
    name: "Comoros",
    iso2CountryCode: "KM",
    iso3CountryCode: "COM",
    phoneCode: "+269",
    flagCode: "U+1F1F0 U+1F1F2",
  },
  {
    name: "Congo",
    iso2CountryCode: "CG",
    iso3CountryCode: "COG",
    phoneCode: "+242",
    flagCode: "U+1F1E8 U+1F1EC",
  },
  {
    name: "Cook Islands",
    iso2CountryCode: "CK",
    iso3CountryCode: "COK",
    phoneCode: "+682",
    flagCode: "U+1F1E8 U+1F1F0",
  },
  {
    name: "Costa Rica",
    iso2CountryCode: "CR",
    iso3CountryCode: "CRI",
    phoneCode: "+506",
    flagCode: "U+1F1E8 U+1F1F7",
  },
  {
    name: "Croatia",
    iso2CountryCode: "HR",
    iso3CountryCode: "HRV",
    phoneCode: "+385",
    flagCode: "U+1F1ED U+1F1F7",
  },
  {
    name: "Cuba",
    iso2CountryCode: "CU",
    iso3CountryCode: "CUB",
    phoneCode: "+53",
    flagCode: "U+1F1E8 U+1F1FA",
  },
  {
    name: "Curaçao",
    iso2CountryCode: "CW",
    iso3CountryCode: "CUW",
    phoneCode: "+599",
    flagCode: "U+1F1E8 U+1F1FC",
  },
  {
    name: "Cyprus",
    iso2CountryCode: "CY",
    iso3CountryCode: "CYP",
    phoneCode: "+357",
    flagCode: "U+1F1E8 U+1F1FE",
  },
  {
    name: "Czech Republic",
    iso2CountryCode: "CZ",
    iso3CountryCode: "CZE",
    phoneCode: "+420",
    flagCode: "U+1F1E8 U+1F1FF",
  },
  {
    name: "Democratic Republic of the Congo",
    iso2CountryCode: "CD",
    iso3CountryCode: "COD",
    phoneCode: "+243",
    flagCode: "U+1F1E8 U+1F1E9",
  },
  {
    name: "Denmark",
    iso2CountryCode: "DK",
    iso3CountryCode: "DNK",
    phoneCode: "+45",
    flagCode: "U+1F1E9 U+1F1F0",
  },
  {
    name: "Djibouti",
    iso2CountryCode: "DJ",
    iso3CountryCode: "DJI",
    phoneCode: "+253",
    flagCode: "U+1F1E9 U+1F1EF",
  },
  {
    name: "Dominica",
    iso2CountryCode: "DM",
    iso3CountryCode: "DMA",
    phoneCode: "+1",
    flagCode: "U+1F1E9 U+1F1F2",
  },
  {
    name: "Dominican Republic",
    iso2CountryCode: "DO",
    iso3CountryCode: "DOM",
    phoneCode: "+1",
    flagCode: "U+1F1E9 U+1F1F4",
  },
  {
    name: "Ecuador",
    iso2CountryCode: "EC",
    iso3CountryCode: "ECU",
    phoneCode: "+593",
    flagCode: "U+1F1EA U+1F1E8",
  },
  {
    name: "Egypt",
    iso2CountryCode: "EG",
    iso3CountryCode: "EGY",
    phoneCode: "+20",
    flagCode: "U+1F1EA U+1F1EC",
  },
  {
    name: "El Salvador",
    iso2CountryCode: "SV",
    iso3CountryCode: "SLV",
    phoneCode: "+503",
    flagCode: "U+1F1F8 U+1F1FB",
  },
  {
    name: "Equatorial Guinea",
    iso2CountryCode: "GQ",
    iso3CountryCode: "GNQ",
    phoneCode: "+240",
    flagCode: "U+1F1EC U+1F1F6",
  },
  {
    name: "Eritrea",
    iso2CountryCode: "ER",
    iso3CountryCode: "ERI",
    phoneCode: "+291",
    flagCode: "U+1F1EA U+1F1F7",
  },
  {
    name: "Estonia",
    iso2CountryCode: "EE",
    iso3CountryCode: "EST",
    phoneCode: "+372",
    flagCode: "U+1F1EA U+1F1EA",
  },
  {
    name: "Eswatini",
    iso2CountryCode: "SZ",
    iso3CountryCode: "SWZ",
    phoneCode: "+268",
    flagCode: "U+1F1F8 U+1F1FF",
  },
  {
    name: "Ethiopia",
    iso2CountryCode: "ET",
    iso3CountryCode: "ETH",
    phoneCode: "+251",
    flagCode: "U+1F1EA U+1F1F9",
  },
  {
    name: "Falkland Islands",
    iso2CountryCode: "FK",
    iso3CountryCode: "FLK",
    phoneCode: "+500",
    flagCode: "U+1F1EB U+1F1F0",
  },
  {
    name: "Faroe Islands",
    iso2CountryCode: "FO",
    iso3CountryCode: "FRO",
    phoneCode: "+298",
    flagCode: "U+1F1EB U+1F1F4",
  },
  {
    name: "Fiji Islands",
    iso2CountryCode: "FJ",
    iso3CountryCode: "FJI",
    phoneCode: "+679",
    flagCode: "U+1F1EB U+1F1EF",
  },
  {
    name: "Finland",
    iso2CountryCode: "FI",
    iso3CountryCode: "FIN",
    phoneCode: "+358",
    flagCode: "U+1F1EB U+1F1EE",
  },
  {
    name: "France",
    iso2CountryCode: "FR",
    iso3CountryCode: "FRA",
    phoneCode: "+33",
    flagCode: "U+1F1EB U+1F1F7",
  },
  {
    name: "French Guiana",
    iso2CountryCode: "GF",
    iso3CountryCode: "GUF",
    phoneCode: "+594",
    flagCode: "U+1F1EC U+1F1EB",
  },
  {
    name: "French Polynesia",
    iso2CountryCode: "PF",
    iso3CountryCode: "PYF",
    phoneCode: "+689",
    flagCode: "U+1F1F5 U+1F1EB",
  },
  {
    name: "French Southern Territories",
    iso2CountryCode: "TF",
    iso3CountryCode: "ATF",
    phoneCode: "+262",
    flagCode: "U+1F1F9 U+1F1EB",
  },
  {
    name: "Gabon",
    iso2CountryCode: "GA",
    iso3CountryCode: "GAB",
    phoneCode: "+241",
    flagCode: "U+1F1EC U+1F1E6",
  },
  {
    name: "Georgia",
    iso2CountryCode: "GE",
    iso3CountryCode: "GEO",
    phoneCode: "+995",
    flagCode: "U+1F1EC U+1F1EA",
  },
  {
    name: "Germany",
    iso2CountryCode: "DE",
    iso3CountryCode: "DEU",
    phoneCode: "+49",
    flagCode: "U+1F1E9 U+1F1EA",
  },
  {
    name: "Ghana",
    iso2CountryCode: "GH",
    iso3CountryCode: "GHA",
    phoneCode: "+233",
    flagCode: "U+1F1EC U+1F1ED",
  },
  {
    name: "Gibraltar",
    iso2CountryCode: "GI",
    iso3CountryCode: "GIB",
    phoneCode: "+350",
    flagCode: "U+1F1EC U+1F1EE",
  },
  {
    name: "Greece",
    iso2CountryCode: "GR",
    iso3CountryCode: "GRC",
    phoneCode: "+30",
    flagCode: "U+1F1EC U+1F1F7",
  },
  {
    name: "Greenland",
    iso2CountryCode: "GL",
    iso3CountryCode: "GRL",
    phoneCode: "+299",
    flagCode: "U+1F1EC U+1F1F1",
  },
  {
    name: "Grenada",
    iso2CountryCode: "GD",
    iso3CountryCode: "GRD",
    phoneCode: "+1",
    flagCode: "U+1F1EC U+1F1E9",
  },
  {
    name: "Guadeloupe",
    iso2CountryCode: "GP",
    iso3CountryCode: "GLP",
    phoneCode: "+590",
    flagCode: "U+1F1EC U+1F1F5",
  },
  {
    name: "Guam",
    iso2CountryCode: "GU",
    iso3CountryCode: "GUM",
    phoneCode: "+1",
    flagCode: "U+1F1EC U+1F1FA",
  },
  {
    name: "Guatemala",
    iso2CountryCode: "GT",
    iso3CountryCode: "GTM",
    phoneCode: "+502",
    flagCode: "U+1F1EC U+1F1F9",
  },
  {
    name: "Guernsey",
    iso2CountryCode: "GG",
    iso3CountryCode: "GGY",
    phoneCode: "+44",
    flagCode: "U+1F1EC U+1F1EC",
  },
  {
    name: "Guinea",
    iso2CountryCode: "GN",
    iso3CountryCode: "GIN",
    phoneCode: "+224",
    flagCode: "U+1F1EC U+1F1F3",
  },
  {
    name: "Guinea-Bissau",
    iso2CountryCode: "GW",
    iso3CountryCode: "GNB",
    phoneCode: "+245",
    flagCode: "U+1F1EC U+1F1FC",
  },
  {
    name: "Guyana",
    iso2CountryCode: "GY",
    iso3CountryCode: "GUY",
    phoneCode: "+592",
    flagCode: "U+1F1EC U+1F1FE",
  },
  {
    name: "Haiti",
    iso2CountryCode: "HT",
    iso3CountryCode: "HTI",
    phoneCode: "+509",
    flagCode: "U+1F1ED U+1F1F9",
  },
  {
    name: "Heard Island and McDonald Islands",
    iso2CountryCode: "HM",
    iso3CountryCode: "HMD",
    phoneCode: "+672",
    flagCode: "U+1F1ED U+1F1F2",
  },
  {
    name: "Honduras",
    iso2CountryCode: "HN",
    iso3CountryCode: "HND",
    phoneCode: "+504",
    flagCode: "U+1F1ED U+1F1F3",
  },
  {
    name: "Hong Kong S.A.R.",
    iso2CountryCode: "HK",
    iso3CountryCode: "HKG",
    phoneCode: "+852",
    flagCode: "U+1F1ED U+1F1F0",
  },
  {
    name: "Hungary",
    iso2CountryCode: "HU",
    iso3CountryCode: "HUN",
    phoneCode: "+36",
    flagCode: "U+1F1ED U+1F1FA",
  },
  {
    name: "Iceland",
    iso2CountryCode: "IS",
    iso3CountryCode: "ISL",
    phoneCode: "+354",
    flagCode: "U+1F1EE U+1F1F8",
  },
  {
    name: "India",
    iso2CountryCode: "IN",
    iso3CountryCode: "IND",
    phoneCode: "+91",
    flagCode: "U+1F1EE U+1F1F3",
  },
  {
    name: "Indonesia",
    iso2CountryCode: "ID",
    iso3CountryCode: "IDN",
    phoneCode: "+62",
    flagCode: "U+1F1EE U+1F1E9",
  },
  {
    name: "Iran",
    iso2CountryCode: "IR",
    iso3CountryCode: "IRN",
    phoneCode: "+98",
    flagCode: "U+1F1EE U+1F1F7",
  },
  {
    name: "Iraq",
    iso2CountryCode: "IQ",
    iso3CountryCode: "IRQ",
    phoneCode: "+964",
    flagCode: "U+1F1EE U+1F1F6",
  },
  {
    name: "Ireland",
    iso2CountryCode: "IE",
    iso3CountryCode: "IRL",
    phoneCode: "+353",
    flagCode: "U+1F1EE U+1F1EA",
  },
  {
    name: "Israel",
    iso2CountryCode: "IL",
    iso3CountryCode: "ISR",
    phoneCode: "+972",
    flagCode: "U+1F1EE U+1F1F1",
  },
  {
    name: "Italy",
    iso2CountryCode: "IT",
    iso3CountryCode: "ITA",
    phoneCode: "+39",
    flagCode: "U+1F1EE U+1F1F9",
  },
  {
    name: "Ivory Coast",
    iso2CountryCode: "CI",
    iso3CountryCode: "CIV",
    phoneCode: "+225",
    flagCode: "U+1F1E8 U+1F1EE",
  },
  {
    name: "Jamaica",
    iso2CountryCode: "JM",
    iso3CountryCode: "JAM",
    phoneCode: "+1",
    flagCode: "U+1F1EF U+1F1F2",
  },
  {
    name: "Japan",
    iso2CountryCode: "JP",
    iso3CountryCode: "JPN",
    phoneCode: "+81",
    flagCode: "U+1F1EF U+1F1F5",
  },
  {
    name: "Jersey",
    iso2CountryCode: "JE",
    iso3CountryCode: "JEY",
    phoneCode: "+44",
    flagCode: "U+1F1EF U+1F1EA",
  },
  {
    name: "Jordan",
    iso2CountryCode: "JO",
    iso3CountryCode: "JOR",
    phoneCode: "+962",
    flagCode: "U+1F1EF U+1F1F4",
  },
  {
    name: "Kazakhstan",
    iso2CountryCode: "KZ",
    iso3CountryCode: "KAZ",
    phoneCode: "+7",
    flagCode: "U+1F1F0 U+1F1FF",
  },
  {
    name: "Kenya",
    iso2CountryCode: "KE",
    iso3CountryCode: "KEN",
    phoneCode: "+254",
    flagCode: "U+1F1F0 U+1F1EA",
  },
  {
    name: "Kiribati",
    iso2CountryCode: "KI",
    iso3CountryCode: "KIR",
    phoneCode: "+686",
    flagCode: "U+1F1F0 U+1F1EE",
  },
  {
    name: "Kosovo",
    iso2CountryCode: "XK",
    iso3CountryCode: "XKX",
    phoneCode: "+383",
    flagCode: "U+1F1FD U+1F1F0",
  },
  {
    name: "Kuwait",
    iso2CountryCode: "KW",
    iso3CountryCode: "KWT",
    phoneCode: "+965",
    flagCode: "U+1F1F0 U+1F1FC",
  },
  {
    name: "Kyrgyzstan",
    iso2CountryCode: "KG",
    iso3CountryCode: "KGZ",
    phoneCode: "+996",
    flagCode: "U+1F1F0 U+1F1EC",
  },
  {
    name: "Laos",
    iso2CountryCode: "LA",
    iso3CountryCode: "LAO",
    phoneCode: "+856",
    flagCode: "U+1F1F1 U+1F1E6",
  },
  {
    name: "Latvia",
    iso2CountryCode: "LV",
    iso3CountryCode: "LVA",
    phoneCode: "+371",
    flagCode: "U+1F1F1 U+1F1FB",
  },
  {
    name: "Lebanon",
    iso2CountryCode: "LB",
    iso3CountryCode: "LBN",
    phoneCode: "+961",
    flagCode: "U+1F1F1 U+1F1E7",
  },
  {
    name: "Lesotho",
    iso2CountryCode: "LS",
    iso3CountryCode: "LSO",
    phoneCode: "+266",
    flagCode: "U+1F1F1 U+1F1F8",
  },
  {
    name: "Liberia",
    iso2CountryCode: "LR",
    iso3CountryCode: "LBR",
    phoneCode: "+231",
    flagCode: "U+1F1F1 U+1F1F7",
  },
  {
    name: "Libya",
    iso2CountryCode: "LY",
    iso3CountryCode: "LBY",
    phoneCode: "+218",
    flagCode: "U+1F1F1 U+1F1FE",
  },
  {
    name: "Liechtenstein",
    iso2CountryCode: "LI",
    iso3CountryCode: "LIE",
    phoneCode: "+423",
    flagCode: "U+1F1F1 U+1F1EE",
  },
  {
    name: "Lithuania",
    iso2CountryCode: "LT",
    iso3CountryCode: "LTU",
    phoneCode: "+370",
    flagCode: "U+1F1F1 U+1F1F9",
  },
  {
    name: "Luxembourg",
    iso2CountryCode: "LU",
    iso3CountryCode: "LUX",
    phoneCode: "+352",
    flagCode: "U+1F1F1 U+1F1FA",
  },
  {
    name: "Macau S.A.R.",
    iso2CountryCode: "MO",
    iso3CountryCode: "MAC",
    phoneCode: "+853",
    flagCode: "U+1F1F2 U+1F1F4",
  },
  {
    name: "Madagascar",
    iso2CountryCode: "MG",
    iso3CountryCode: "MDG",
    phoneCode: "+261",
    flagCode: "U+1F1F2 U+1F1EC",
  },
  {
    name: "Malawi",
    iso2CountryCode: "MW",
    iso3CountryCode: "MWI",
    phoneCode: "+265",
    flagCode: "U+1F1F2 U+1F1FC",
  },
  {
    name: "Malaysia",
    iso2CountryCode: "MY",
    iso3CountryCode: "MYS",
    phoneCode: "+60",
    flagCode: "U+1F1F2 U+1F1FE",
  },
  {
    name: "Maldives",
    iso2CountryCode: "MV",
    iso3CountryCode: "MDV",
    phoneCode: "+960",
    flagCode: "U+1F1F2 U+1F1FB",
  },
  {
    name: "Mali",
    iso2CountryCode: "ML",
    iso3CountryCode: "MLI",
    phoneCode: "+223",
    flagCode: "U+1F1F2 U+1F1F1",
  },
  {
    name: "Malta",
    iso2CountryCode: "MT",
    iso3CountryCode: "MLT",
    phoneCode: "+356",
    flagCode: "U+1F1F2 U+1F1F9",
  },
  {
    name: "Man (Isle of)",
    iso2CountryCode: "IM",
    iso3CountryCode: "IMN",
    phoneCode: "+44",
    flagCode: "U+1F1EE U+1F1F2",
  },
  {
    name: "Marshall Islands",
    iso2CountryCode: "MH",
    iso3CountryCode: "MHL",
    phoneCode: "+692",
    flagCode: "U+1F1F2 U+1F1ED",
  },
  {
    name: "Martinique",
    iso2CountryCode: "MQ",
    iso3CountryCode: "MTQ",
    phoneCode: "+596",
    flagCode: "U+1F1F2 U+1F1F6",
  },
  {
    name: "Mauritania",
    iso2CountryCode: "MR",
    iso3CountryCode: "MRT",
    phoneCode: "+222",
    flagCode: "U+1F1F2 U+1F1F7",
  },
  {
    name: "Mauritius",
    iso2CountryCode: "MU",
    iso3CountryCode: "MUS",
    phoneCode: "+230",
    flagCode: "U+1F1F2 U+1F1FA",
  },
  {
    name: "Mayotte",
    iso2CountryCode: "YT",
    iso3CountryCode: "MYT",
    phoneCode: "+262",
    flagCode: "U+1F1FE U+1F1F9",
  },
  {
    name: "Mexico",
    iso2CountryCode: "MX",
    iso3CountryCode: "MEX",
    phoneCode: "+52",
    flagCode: "U+1F1F2 U+1F1FD",
  },
  {
    name: "Micronesia",
    iso2CountryCode: "FM",
    iso3CountryCode: "FSM",
    phoneCode: "+691",
    flagCode: "U+1F1EB U+1F1F2",
  },
  {
    name: "Moldova",
    iso2CountryCode: "MD",
    iso3CountryCode: "MDA",
    phoneCode: "+373",
    flagCode: "U+1F1F2 U+1F1E9",
  },
  {
    name: "Monaco",
    iso2CountryCode: "MC",
    iso3CountryCode: "MCO",
    phoneCode: "+377",
    flagCode: "U+1F1F2 U+1F1E8",
  },
  {
    name: "Mongolia",
    iso2CountryCode: "MN",
    iso3CountryCode: "MNG",
    phoneCode: "+976",
    flagCode: "U+1F1F2 U+1F1F3",
  },
  {
    name: "Montenegro",
    iso2CountryCode: "ME",
    iso3CountryCode: "MNE",
    phoneCode: "+382",
    flagCode: "U+1F1F2 U+1F1EA",
  },
  {
    name: "Montserrat",
    iso2CountryCode: "MS",
    iso3CountryCode: "MSR",
    phoneCode: "+1",
    flagCode: "U+1F1F2 U+1F1F8",
  },
  {
    name: "Morocco",
    iso2CountryCode: "MA",
    iso3CountryCode: "MAR",
    phoneCode: "+212",
    flagCode: "U+1F1F2 U+1F1E6",
  },
  {
    name: "Mozambique",
    iso2CountryCode: "MZ",
    iso3CountryCode: "MOZ",
    phoneCode: "+258",
    flagCode: "U+1F1F2 U+1F1FF",
  },
  {
    name: "Myanmar",
    iso2CountryCode: "MM",
    iso3CountryCode: "MMR",
    phoneCode: "+95",
    flagCode: "U+1F1F2 U+1F1F2",
  },
  {
    name: "Namibia",
    iso2CountryCode: "NA",
    iso3CountryCode: "NAM",
    phoneCode: "+264",
    flagCode: "U+1F1F3 U+1F1E6",
  },
  {
    name: "Nauru",
    iso2CountryCode: "NR",
    iso3CountryCode: "NRU",
    phoneCode: "+674",
    flagCode: "U+1F1F3 U+1F1F7",
  },
  {
    name: "Nepal",
    iso2CountryCode: "NP",
    iso3CountryCode: "NPL",
    phoneCode: "+977",
    flagCode: "U+1F1F3 U+1F1F5",
  },
  {
    name: "Netherlands",
    iso2CountryCode: "NL",
    iso3CountryCode: "NLD",
    phoneCode: "+31",
    flagCode: "U+1F1F3 U+1F1F1",
  },
  {
    name: "New Caledonia",
    iso2CountryCode: "NC",
    iso3CountryCode: "NCL",
    phoneCode: "+687",
    flagCode: "U+1F1F3 U+1F1E8",
  },
  {
    name: "New Zealand",
    iso2CountryCode: "NZ",
    iso3CountryCode: "NZL",
    phoneCode: "+64",
    flagCode: "U+1F1F3 U+1F1FF",
  },
  {
    name: "Nicaragua",
    iso2CountryCode: "NI",
    iso3CountryCode: "NIC",
    phoneCode: "+505",
    flagCode: "U+1F1F3 U+1F1EE",
  },
  {
    name: "Niger",
    iso2CountryCode: "NE",
    iso3CountryCode: "NER",
    phoneCode: "+227",
    flagCode: "U+1F1F3 U+1F1EA",
  },
  {
    name: "Nigeria",
    iso2CountryCode: "NG",
    iso3CountryCode: "NGA",
    phoneCode: "+234",
    flagCode: "U+1F1F3 U+1F1EC",
  },
  {
    name: "Niue",
    iso2CountryCode: "NU",
    iso3CountryCode: "NIU",
    phoneCode: "+683",
    flagCode: "U+1F1F3 U+1F1FA",
  },
  {
    name: "Norfolk Island",
    iso2CountryCode: "NF",
    iso3CountryCode: "NFK",
    phoneCode: "+672",
    flagCode: "U+1F1F3 U+1F1EB",
  },
  {
    name: "North Korea",
    iso2CountryCode: "KP",
    iso3CountryCode: "PRK",
    phoneCode: "+850",
    flagCode: "U+1F1F0 U+1F1F5",
  },
  {
    name: "North Macedonia",
    iso2CountryCode: "MK",
    iso3CountryCode: "MKD",
    phoneCode: "+389",
    flagCode: "U+1F1F2 U+1F1F0",
  },
  {
    name: "Northern Mariana Islands",
    iso2CountryCode: "MP",
    iso3CountryCode: "MNP",
    phoneCode: "+1",
    flagCode: "U+1F1F2 U+1F1F5",
  },
  {
    name: "Norway",
    iso2CountryCode: "NO",
    iso3CountryCode: "NOR",
    phoneCode: "+47",
    flagCode: "U+1F1F3 U+1F1F4",
  },
  {
    name: "Oman",
    iso2CountryCode: "OM",
    iso3CountryCode: "OMN",
    phoneCode: "+968",
    flagCode: "U+1F1F4 U+1F1F2",
  },
  {
    name: "Pakistan",
    iso2CountryCode: "PK",
    iso3CountryCode: "PAK",
    phoneCode: "+92",
    flagCode: "U+1F1F5 U+1F1F0",
  },
  {
    name: "Palau",
    iso2CountryCode: "PW",
    iso3CountryCode: "PLW",
    phoneCode: "+680",
    flagCode: "U+1F1F5 U+1F1FC",
  },
  {
    name: "Palestinian Territory Occupied",
    iso2CountryCode: "PS",
    iso3CountryCode: "PSE",
    phoneCode: "+970",
    flagCode: "U+1F1F5 U+1F1F8",
  },
  {
    name: "Panama",
    iso2CountryCode: "PA",
    iso3CountryCode: "PAN",
    phoneCode: "+507",
    flagCode: "U+1F1F5 U+1F1E6",
  },
  {
    name: "Papua New Guinea",
    iso2CountryCode: "PG",
    iso3CountryCode: "PNG",
    phoneCode: "+675",
    flagCode: "U+1F1F5 U+1F1EC",
  },
  {
    name: "Paraguay",
    iso2CountryCode: "PY",
    iso3CountryCode: "PRY",
    phoneCode: "+595",
    flagCode: "U+1F1F5 U+1F1FE",
  },
  {
    name: "Peru",
    iso2CountryCode: "PE",
    iso3CountryCode: "PER",
    phoneCode: "+51",
    flagCode: "U+1F1F5 U+1F1EA",
  },
  {
    name: "Philippines",
    iso2CountryCode: "PH",
    iso3CountryCode: "PHL",
    phoneCode: "+63",
    flagCode: "U+1F1F5 U+1F1ED",
  },
  {
    name: "Pitcairn Island",
    iso2CountryCode: "PN",
    iso3CountryCode: "PCN",
    phoneCode: "+870",
    flagCode: "U+1F1F5 U+1F1F3",
  },
  {
    name: "Poland",
    iso2CountryCode: "PL",
    iso3CountryCode: "POL",
    phoneCode: "+48",
    flagCode: "U+1F1F5 U+1F1F1",
  },
  {
    name: "Portugal",
    iso2CountryCode: "PT",
    iso3CountryCode: "PRT",
    phoneCode: "+351",
    flagCode: "U+1F1F5 U+1F1F9",
  },
  {
    name: "Puerto Rico",
    iso2CountryCode: "PR",
    iso3CountryCode: "PRI",
    phoneCode: "+1",
    flagCode: "U+1F1F5 U+1F1F7",
  },
  {
    name: "Qatar",
    iso2CountryCode: "QA",
    iso3CountryCode: "QAT",
    phoneCode: "+974",
    flagCode: "U+1F1F6 U+1F1E6",
  },
  {
    name: "Reunion",
    iso2CountryCode: "RE",
    iso3CountryCode: "REU",
    phoneCode: "+262",
    flagCode: "U+1F1F7 U+1F1EA",
  },
  {
    name: "Romania",
    iso2CountryCode: "RO",
    iso3CountryCode: "ROU",
    phoneCode: "+40",
    flagCode: "U+1F1F7 U+1F1F4",
  },
  {
    name: "Russia",
    iso2CountryCode: "RU",
    iso3CountryCode: "RUS",
    phoneCode: "+7",
    flagCode: "U+1F1F7 U+1F1FA",
  },
  {
    name: "Rwanda",
    iso2CountryCode: "RW",
    iso3CountryCode: "RWA",
    phoneCode: "+250",
    flagCode: "U+1F1F7 U+1F1FC",
  },
  {
    name: "Saint Helena",
    iso2CountryCode: "SH",
    iso3CountryCode: "SHN",
    phoneCode: "+290",
    flagCode: "U+1F1F8 U+1F1ED",
  },
  {
    name: "Saint Kitts and Nevis",
    iso2CountryCode: "KN",
    iso3CountryCode: "KNA",
    phoneCode: "+1",
    flagCode: "U+1F1F0 U+1F1F3",
  },
  {
    name: "Saint Lucia",
    iso2CountryCode: "LC",
    iso3CountryCode: "LCA",
    phoneCode: "+1",
    flagCode: "U+1F1F1 U+1F1E8",
  },
  {
    name: "Saint Pierre and Miquelon",
    iso2CountryCode: "PM",
    iso3CountryCode: "SPM",
    phoneCode: "+508",
    flagCode: "U+1F1F5 U+1F1F2",
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso2CountryCode: "VC",
    iso3CountryCode: "VCT",
    phoneCode: "+1",
    flagCode: "U+1F1FB U+1F1E8",
  },
  {
    name: "Saint-Barthelemy",
    iso2CountryCode: "BL",
    iso3CountryCode: "BLM",
    phoneCode: "+590",
    flagCode: "U+1F1E7 U+1F1F1",
  },
  {
    name: "Saint-Martin (French part)",
    iso2CountryCode: "MF",
    iso3CountryCode: "MAF",
    phoneCode: "+590",
    flagCode: "U+1F1F2 U+1F1EB",
  },
  {
    name: "Samoa",
    iso2CountryCode: "WS",
    iso3CountryCode: "WSM",
    phoneCode: "+685",
    flagCode: "U+1F1FC U+1F1F8",
  },
  {
    name: "San Marino",
    iso2CountryCode: "SM",
    iso3CountryCode: "SMR",
    phoneCode: "+378",
    flagCode: "U+1F1F8 U+1F1F2",
  },
  {
    name: "Sao Tome and Principe",
    iso2CountryCode: "ST",
    iso3CountryCode: "STP",
    phoneCode: "+239",
    flagCode: "U+1F1F8 U+1F1F9",
  },
  {
    name: "Saudi Arabia",
    iso2CountryCode: "SA",
    iso3CountryCode: "SAU",
    phoneCode: "+966",
    flagCode: "U+1F1F8 U+1F1E6",
  },
  {
    name: "Senegal",
    iso2CountryCode: "SN",
    iso3CountryCode: "SEN",
    phoneCode: "+221",
    flagCode: "U+1F1F8 U+1F1F3",
  },
  {
    name: "Serbia",
    iso2CountryCode: "RS",
    iso3CountryCode: "SRB",
    phoneCode: "+381",
    flagCode: "U+1F1F7 U+1F1F8",
  },
  {
    name: "Seychelles",
    iso2CountryCode: "SC",
    iso3CountryCode: "SYC",
    phoneCode: "+248",
    flagCode: "U+1F1F8 U+1F1E8",
  },
  {
    name: "Sierra Leone",
    iso2CountryCode: "SL",
    iso3CountryCode: "SLE",
    phoneCode: "+232",
    flagCode: "U+1F1F8 U+1F1F1",
  },
  {
    name: "Singapore",
    iso2CountryCode: "SG",
    iso3CountryCode: "SGP",
    phoneCode: "+65",
    flagCode: "U+1F1F8 U+1F1EC",
  },
  {
    name: "Sint Maarten (Dutch part)",
    iso2CountryCode: "SX",
    iso3CountryCode: "SXM",
    phoneCode: "+1721",
    flagCode: "U+1F1F8 U+1F1FD",
  },
  {
    name: "Slovakia",
    iso2CountryCode: "SK",
    iso3CountryCode: "SVK",
    phoneCode: "+421",
    flagCode: "U+1F1F8 U+1F1F0",
  },
  {
    name: "Slovenia",
    iso2CountryCode: "SI",
    iso3CountryCode: "SVN",
    phoneCode: "+386",
    flagCode: "U+1F1F8 U+1F1EE",
  },
  {
    name: "Solomon Islands",
    iso2CountryCode: "SB",
    iso3CountryCode: "SLB",
    phoneCode: "+677",
    flagCode: "U+1F1F8 U+1F1E7",
  },
  {
    name: "Somalia",
    iso2CountryCode: "SO",
    iso3CountryCode: "SOM",
    phoneCode: "+252",
    flagCode: "U+1F1F8 U+1F1F4",
  },
  {
    name: "South Africa",
    iso2CountryCode: "ZA",
    iso3CountryCode: "ZAF",
    phoneCode: "+27",
    flagCode: "U+1F1FF U+1F1E6",
  },
  {
    name: "South Georgia",
    iso2CountryCode: "GS",
    iso3CountryCode: "SGS",
    phoneCode: "+500",
    flagCode: "U+1F1EC U+1F1F8",
  },
  {
    name: "South Korea",
    iso2CountryCode: "KR",
    iso3CountryCode: "KOR",
    phoneCode: "+82",
    flagCode: "U+1F1F0 U+1F1F7",
  },
  {
    name: "South Sudan",
    iso2CountryCode: "SS",
    iso3CountryCode: "SSD",
    phoneCode: "+211",
    flagCode: "U+1F1F8 U+1F1F8",
  },
  {
    name: "Spain",
    iso2CountryCode: "ES",
    iso3CountryCode: "ESP",
    phoneCode: "+34",
    flagCode: "U+1F1EA U+1F1F8",
  },
  {
    name: "Sri Lanka",
    iso2CountryCode: "LK",
    iso3CountryCode: "LKA",
    phoneCode: "+94",
    flagCode: "U+1F1F1 U+1F1F0",
  },
  {
    name: "Sudan",
    iso2CountryCode: "SD",
    iso3CountryCode: "SDN",
    phoneCode: "+249",
    flagCode: "U+1F1F8 U+1F1E9",
  },
  {
    name: "Suriname",
    iso2CountryCode: "SR",
    iso3CountryCode: "SUR",
    phoneCode: "+597",
    flagCode: "U+1F1F8 U+1F1F7",
  },
  {
    name: "Svalbard and Jan Mayen Islands",
    iso2CountryCode: "SJ",
    iso3CountryCode: "SJM",
    phoneCode: "+47",
    flagCode: "U+1F1F8 U+1F1EF",
  },
  {
    name: "Sweden",
    iso2CountryCode: "SE",
    iso3CountryCode: "SWE",
    phoneCode: "+46",
    flagCode: "U+1F1F8 U+1F1EA",
  },
  {
    name: "Switzerland",
    iso2CountryCode: "CH",
    iso3CountryCode: "CHE",
    phoneCode: "+41",
    flagCode: "U+1F1E8 U+1F1ED",
  },
  {
    name: "Syria",
    iso2CountryCode: "SY",
    iso3CountryCode: "SYR",
    phoneCode: "+963",
    flagCode: "U+1F1F8 U+1F1FE",
  },
  {
    name: "Taiwan",
    iso2CountryCode: "TW",
    iso3CountryCode: "TWN",
    phoneCode: "+886",
    flagCode: "U+1F1F9 U+1F1FC",
  },
  {
    name: "Tajikistan",
    iso2CountryCode: "TJ",
    iso3CountryCode: "TJK",
    phoneCode: "+992",
    flagCode: "U+1F1F9 U+1F1EF",
  },
  {
    name: "Tanzania",
    iso2CountryCode: "TZ",
    iso3CountryCode: "TZA",
    phoneCode: "+255",
    flagCode: "U+1F1F9 U+1F1FF",
  },
  {
    name: "Thailand",
    iso2CountryCode: "TH",
    iso3CountryCode: "THA",
    phoneCode: "+66",
    flagCode: "U+1F1F9 U+1F1ED",
  },
  {
    name: "The Bahamas",
    iso2CountryCode: "BS",
    iso3CountryCode: "BHS",
    phoneCode: "+1",
    flagCode: "U+1F1E7 U+1F1F8",
  },
  {
    name: "The Gambia",
    iso2CountryCode: "GM",
    iso3CountryCode: "GMB",
    phoneCode: "+220",
    flagCode: "U+1F1EC U+1F1F2",
  },
  {
    name: "Timor-Leste",
    iso2CountryCode: "TL",
    iso3CountryCode: "TLS",
    phoneCode: "+670",
    flagCode: "U+1F1F9 U+1F1F1",
  },
  {
    name: "Togo",
    iso2CountryCode: "TG",
    iso3CountryCode: "TGO",
    phoneCode: "+228",
    flagCode: "U+1F1F9 U+1F1EC",
  },
  {
    name: "Tokelau",
    iso2CountryCode: "TK",
    iso3CountryCode: "TKL",
    phoneCode: "+690",
    flagCode: "U+1F1F9 U+1F1F0",
  },
  {
    name: "Tonga",
    iso2CountryCode: "TO",
    iso3CountryCode: "TON",
    phoneCode: "+676",
    flagCode: "U+1F1F9 U+1F1F4",
  },
  {
    name: "Trinidad and Tobago",
    iso2CountryCode: "TT",
    iso3CountryCode: "TTO",
    phoneCode: "+1",
    flagCode: "U+1F1F9 U+1F1F9",
  },
  {
    name: "Tunisia",
    iso2CountryCode: "TN",
    iso3CountryCode: "TUN",
    phoneCode: "+216",
    flagCode: "U+1F1F9 U+1F1F3",
  },
  {
    name: "Turkey",
    iso2CountryCode: "TR",
    iso3CountryCode: "TUR",
    phoneCode: "+90",
    flagCode: "U+1F1F9 U+1F1F7",
  },
  {
    name: "Turkmenistan",
    iso2CountryCode: "TM",
    iso3CountryCode: "TKM",
    phoneCode: "+993",
    flagCode: "U+1F1F9 U+1F1F2",
  },
  {
    name: "Turks and Caicos Islands",
    iso2CountryCode: "TC",
    iso3CountryCode: "TCA",
    phoneCode: "+1",
    flagCode: "U+1F1F9 U+1F1E8",
  },
  {
    name: "Tuvalu",
    iso2CountryCode: "TV",
    iso3CountryCode: "TUV",
    phoneCode: "+688",
    flagCode: "U+1F1F9 U+1F1FB",
  },
  {
    name: "Uganda",
    iso2CountryCode: "UG",
    iso3CountryCode: "UGA",
    phoneCode: "+256",
    flagCode: "U+1F1FA U+1F1EC",
  },
  {
    name: "Ukraine",
    iso2CountryCode: "UA",
    iso3CountryCode: "UKR",
    phoneCode: "+380",
    flagCode: "U+1F1FA U+1F1E6",
  },
  {
    name: "United Arab Emirates",
    iso2CountryCode: "AE",
    iso3CountryCode: "ARE",
    phoneCode: "+971",
    flagCode: "U+1F1E6 U+1F1EA",
  },
  {
    name: "United Kingdom",
    iso2CountryCode: "GB",
    iso3CountryCode: "GBR",
    phoneCode: "+44",
    flagCode: "U+1F1EC U+1F1E7",
  },
  {
    name: "United States",
    iso2CountryCode: "US",
    iso3CountryCode: "USA",
    phoneCode: "+1",
    flagCode: "U+1F1FA U+1F1F8",
  },
  {
    name: "United States Minor Outlying Islands",
    iso2CountryCode: "UM",
    iso3CountryCode: "UMI",
    phoneCode: "+1",
    flagCode: "U+1F1FA U+1F1F2",
  },
  {
    name: "Uruguay",
    iso2CountryCode: "UY",
    iso3CountryCode: "URY",
    phoneCode: "+598",
    flagCode: "U+1F1FA U+1F1FE",
  },
  {
    name: "Uzbekistan",
    iso2CountryCode: "UZ",
    iso3CountryCode: "UZB",
    phoneCode: "+998",
    flagCode: "U+1F1FA U+1F1FF",
  },
  {
    name: "Vanuatu",
    iso2CountryCode: "VU",
    iso3CountryCode: "VUT",
    phoneCode: "+678",
    flagCode: "U+1F1FB U+1F1FA",
  },
  {
    name: "Vatican City State (Holy See)",
    iso2CountryCode: "VA",
    iso3CountryCode: "VAT",
    phoneCode: "+379",
    flagCode: "U+1F1FB U+1F1E6",
  },
  {
    name: "Venezuela",
    iso2CountryCode: "VE",
    iso3CountryCode: "VEN",
    phoneCode: "+58",
    flagCode: "U+1F1FB U+1F1EA",
  },
  {
    name: "Vietnam",
    iso2CountryCode: "VN",
    iso3CountryCode: "VNM",
    phoneCode: "+84",
    flagCode: "U+1F1FB U+1F1F3",
  },
  {
    name: "Virgin Islands (British)",
    iso2CountryCode: "VG",
    iso3CountryCode: "VGB",
    phoneCode: "+1",
    flagCode: "U+1F1FB U+1F1EC",
  },
  {
    name: "Virgin Islands (US)",
    iso2CountryCode: "VI",
    iso3CountryCode: "VIR",
    phoneCode: "+1",
    flagCode: "U+1F1FB U+1F1EE",
  },
  {
    name: "Wallis and Futuna Islands",
    iso2CountryCode: "WF",
    iso3CountryCode: "WLF",
    phoneCode: "+681",
    flagCode: "U+1F1FC U+1F1EB",
  },
  {
    name: "Western Sahara",
    iso2CountryCode: "EH",
    iso3CountryCode: "ESH",
    phoneCode: "+212",
    flagCode: "U+1F1EA U+1F1ED",
  },
  {
    name: "Yemen",
    iso2CountryCode: "YE",
    iso3CountryCode: "YEM",
    phoneCode: "+967",
    flagCode: "U+1F1FE U+1F1EA",
  },
  {
    name: "Zambia",
    iso2CountryCode: "ZM",
    iso3CountryCode: "ZMB",
    phoneCode: "+260",
    flagCode: "U+1F1FF U+1F1F2",
  },
  {
    name: "Zimbabwe",
    iso2CountryCode: "ZW",
    iso3CountryCode: "ZWE",
    phoneCode: "+263",
    flagCode: "U+1F1FF U+1F1FC",
  },
];
