name: Build & Publish Package

on:
  push:
    branches:
      - dev
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    permissions:
      contents: read
      packages: write

    env:
      VITE_AWS_REGION: ${{ secrets.VITE_AWS_REGION }}
      VITE_COGNITO_IDENTITY_POOL_ID: ${{ secrets.VITE_COGNITO_IDENTITY_POOL_ID }}
      VITE_COGNITO_USER_POOL_ID: ${{ secrets.VITE_COGNITO_USER_POOL_ID }}
      VITE_COGNITO_APP_CLIENT_ID: ${{ secrets.VITE_COGNITO_APP_CLIENT_ID }}
      VITE_ID_SCAN_LICENSE_KEY: ${{ secrets.VITE_ID_SCAN_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          registry-url: https://npm.pkg.github.com

      - run: npm ci
      - run: npm run build

      - name: Publish Dev
        if: github.ref_name == 'dev'
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Publish Main
        if: github.ref_name == 'main'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
