name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_AWS_REGION: ${{ secrets.VITE_AWS_REGION }}
      VITE_COGNITO_IDENTITY_POOL_ID: ${{ secrets.VITE_COGNITO_IDENTITY_POOL_ID }}
      VITE_COGNITO_USER_POOL_ID: ${{ secrets.VITE_COGNITO_USER_POOL_ID }}
      VITE_COGNITO_APP_CLIENT_ID: ${{ secrets.VITE_COGNITO_APP_CLIENT_ID }}
      VITE_ID_SCAN_LICENSE_KEY: ${{ secrets.VITE_ID_SCAN_LICENSE_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.1

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build
