name: Publish Package

on:
  push:
    branches:
      - dev
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.1

      - name: Create npm auth
        run: |
          echo "@manptl553-oss:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GH_PAT}" >> ~/.npmrc
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish Dev
        if: github.ref_name == 'dev'
        run: npm publish --tag dev

      - name: Publish Main
        if: github.ref_name == 'main'
        run: npm publish
